name: DigitalTwinPlatform

on: [ workflow_dispatch, push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest , macos-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pip install -e .[dev,test]

      - name: Run test suite
        run: |
          cd tests/digital_twin_tooling
          python -m unittest discover -v -s .

      - name: Build package
        if: ${{ always() }}
        run: |
          python -m build

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: ./tests/digital_twin_tooling/jobs/**/*.*

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: digital-twin-tooling
          path: ./**/dist/digital_twin_tooling-*.whl

